/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateUserDto {
    'email': string;
    'password': string;
    'role': CreateUserDtoRoleEnum;
    'status': CreateUserDtoStatusEnum;
    'language': CreateUserDtoLanguageEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "CreateUserDtoRoleEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateUserDtoStatusEnum",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "CreateUserDtoLanguageEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateUserDtoRoleEnum {
    User = 'user',
    Admin = 'admin',
    Approver = 'approver',
    Director = 'director',
    SuperAdmin = 'superAdmin',
    Archiver = 'archiver'
}
export enum CreateUserDtoStatusEnum {
    Inactive = 'inactive',
    Verified = 'verified',
    Pending = 'pending',
    Approved = 'approved',
    Rejected = 'rejected',
    Expired = 'expired'
}
export enum CreateUserDtoLanguageEnum {
    En = 'en',
    Mk = 'mk'
}

