/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateIndividualUserDto {
    'email': string;
    'password': string;
    'role': CreateIndividualUserDtoRoleEnum;
    'status': CreateIndividualUserDtoStatusEnum;
    'language': CreateIndividualUserDtoLanguageEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "CreateIndividualUserDtoRoleEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateIndividualUserDtoStatusEnum",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "CreateIndividualUserDtoLanguageEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateIndividualUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateIndividualUserDtoRoleEnum {
    User = 'user',
    Admin = 'admin',
    Approver = 'approver',
    Director = 'director',
    SuperAdmin = 'superAdmin',
    Archiver = 'archiver'
}
export enum CreateIndividualUserDtoStatusEnum {
    Inactive = 'inactive',
    Verified = 'verified',
    Pending = 'pending',
    Approved = 'approved',
    Rejected = 'rejected',
    Expired = 'expired'
}
export enum CreateIndividualUserDtoLanguageEnum {
    En = 'en',
    Mk = 'mk'
}

