/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FilterUserDto {
    'roles'?: Array<FilterUserDtoRolesEnum>;
    'statuses'?: Array<FilterUserDtoStatusesEnum>;
    'email'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Array<FilterUserDtoRolesEnum>",
            "format": ""
        },
        {
            "name": "statuses",
            "baseName": "statuses",
            "type": "Array<FilterUserDtoStatusesEnum>",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilterUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FilterUserDtoRolesEnum {
    User = 'user',
    Admin = 'admin',
    Approver = 'approver',
    Director = 'director',
    SuperAdmin = 'superAdmin',
    Archiver = 'archiver'
}
export enum FilterUserDtoStatusesEnum {
    Inactive = 'inactive',
    Verified = 'verified',
    Pending = 'pending',
    Approved = 'approved',
    Rejected = 'rejected',
    Expired = 'expired'
}

