/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HealthControllerCheckV1200ResponseInfoValue } from '../models/HealthControllerCheckV1200ResponseInfoValue';
import { HttpFile } from '../http/http';

export class HealthControllerCheckV1200Response {
    'status'?: string;
    'info'?: { [key: string]: HealthControllerCheckV1200ResponseInfoValue; } | null;
    'error'?: { [key: string]: HealthControllerCheckV1200ResponseInfoValue; } | null;
    'details'?: { [key: string]: HealthControllerCheckV1200ResponseInfoValue; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "{ [key: string]: HealthControllerCheckV1200ResponseInfoValue; }",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "{ [key: string]: HealthControllerCheckV1200ResponseInfoValue; }",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "{ [key: string]: HealthControllerCheckV1200ResponseInfoValue; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HealthControllerCheckV1200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
