/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FilterUserDto } from '../models/FilterUserDto';
import { SortUserDto } from '../models/SortUserDto';
import { HttpFile } from '../http/http';

export class QueryUserDto {
    'page'?: number;
    'limit'?: number;
    'filter'?: FilterUserDto;
    'sort'?: Array<SortUserDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "FilterUserDto",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<SortUserDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}
