/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SortUserDto {
    'orderBy': SortUserDtoOrderByEnum;
    'order'?: SortUserDtoOrderEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderBy",
            "baseName": "orderBy",
            "type": "SortUserDtoOrderByEnum",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "SortUserDtoOrderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SortUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SortUserDtoOrderByEnum {
    Email = 'email',
    Type = 'type',
    RoleId = 'roleId',
    StatusId = 'statusId',
    CreatedAt = 'createdAt',
    UpdatedAt = 'updatedAt',
    DeletedAt = 'deletedAt'
}
export enum SortUserDtoOrderEnum {
    Asc = 'ASC',
    Desc = 'DESC'
}

