/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateUserDto {
    'email'?: string;
    'password'?: string;
    'role'?: UpdateUserDtoRoleEnum;
    'status'?: UpdateUserDtoStatusEnum;
    'language'?: UpdateUserDtoLanguageEnum;
    'statusReason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UpdateUserDtoRoleEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UpdateUserDtoStatusEnum",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "UpdateUserDtoLanguageEnum",
            "format": ""
        },
        {
            "name": "statusReason",
            "baseName": "statusReason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateUserDtoRoleEnum {
    User = 'user',
    Admin = 'admin',
    Approver = 'approver',
    Director = 'director',
    SuperAdmin = 'superAdmin',
    Archiver = 'archiver'
}
export enum UpdateUserDtoStatusEnum {
    Inactive = 'inactive',
    Verified = 'verified',
    Pending = 'pending',
    Approved = 'approved',
    Rejected = 'rejected',
    Expired = 'expired'
}
export enum UpdateUserDtoLanguageEnum {
    En = 'en',
    Mk = 'mk'
}

