/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PageMetaDto } from '../models/PageMetaDto';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class UsersControllerFindAllV1200Response {
    'meta': PageMetaDto;
    'data': Array<User>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PageMetaDto",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<User>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UsersControllerFindAllV1200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
