/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class User {
    'createdAt': Date;
    'updatedAt': Date | null;
    'deletedAt': Date | null;
    'id': number;
    'email': string;
    'role': UserRoleEnum;
    'status': UserStatusEnum;
    'statusReason': string | null;
    'language': UserLanguageEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRoleEnum",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UserStatusEnum",
            "format": ""
        },
        {
            "name": "statusReason",
            "baseName": "statusReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "UserLanguageEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UserRoleEnum {
    User = 'user',
    Admin = 'admin',
    Approver = 'approver',
    Director = 'director',
    SuperAdmin = 'superAdmin',
    Archiver = 'archiver'
}
export enum UserStatusEnum {
    Inactive = 'inactive',
    Verified = 'verified',
    Pending = 'pending',
    Approved = 'approved',
    Rejected = 'rejected',
    Expired = 'expired'
}
export enum UserLanguageEnum {
    En = 'en',
    Mk = 'mk'
}

